# Generated by Django 2.1.7 on 2019-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190227_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookevent',
            old_name='seats',
            new_name='tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
